device: cuda
task: instance_segmentation
weights: "checkpoints/model_final.pth"
architecture: "InstanceSegmentation/pointrend_rcnn_R_50_FPN_1x_coco.yaml"
tta_batch_size: 1
train_pretrained: True
use_wandb: False
wandb_project: tcd_detectron
eval_after_train: True
config: detectron2/detectron_mask_rcnn_tta.yaml
resume: False

