repos:
  - repo: https://github.com/srstevenson/nb-clean
    rev: "2.3.0"
    hooks:
      - id: nb-clean
        args:
            - --remove-empty-cells

  - repo: https://github.com/psf/black
    rev: 22.10.0
    hooks:
      - id: black
        language_version: python3.10
