[experiment]
setup: False
factor: 1

[trainer]
gpus: 1
min_epochs: 1
max_epochs: 500
auto_lr_find: True
auto_scale_batch_size: False
precision: 16

[model]
loss: focal 
segmentation_model: unet
backbone: resnet34
learning_rate: 1e-3
pretrained: True
learning_rate_schedule_patience: 5
encoder_weights: imagenet
in_channels: 3  
num_classes: 2
max_time: 00:23:50:00

[datamodule]
batch_size: 2
num_workers: 2