[project]
name = "tcd_pipeline"
description = "Restor TCD Pipeline"
version = "0.1.0"
authors = [
    { name = "Josh Veitch-Michaelis", email = "josh@restor.eco" }
]
dependencies = [
]

[project.build-dependencies]
dev = [
    "pytest",
    "pytest-cov",
    "coverage-badge"
]

[project.optional-dependencies]
dev = [
    "pre-commit",
]

[tool.pytest.ini_options]
addopts = [
    "-x",
    "--junitxml=reports/junit/junit.xml",
    "--cov=tcd_pipeline"
]
testpaths = [
    "tests",
]