experiment: 
  setup: False
  factor: 1
  sweep: True

trainer: 
  gpus: 1
  min_epochs: 1
  max_epochs: 500
  auto_lr_find: True
  auto_scale_batch_size: False
  precision: 16
  max_time: 00:23:50:00

model: 
  loss: focal 
  segmentation_model: unetplusplus
  backbone: resnet50
  learning_rate: 1e-3
  pretrained: False
  learning_rate_schedule_patience: 5
  in_channels: 3  
  num_classes: 2

datamodule: 
  batch_size: 2
  num_workers: 2