iou_threshold: 0.7
iou_tiles: 0
min-size:
  tree: 30
  canopy: 30
max-size: 100
cache_folder: "./temp"
stateful: true
cleanup: true
debug_images: false
cache_format: pickle
use_nms: true
confidence_threshold: 0.2
segmentation_merge_pad: 32
merge_classes:
  - canopy