VERSION: 2

DATALOADER:
  NUM_WORKERS: 12
SOLVER:
  IMS_PER_BATCH: 32
  MAX_ITER: 40000
  BASE_LR: 0.001

INPUT:
  # Augmentation and input training
  # sizes are controlled in the Trainer
  # class, which overrides the file-based
  # config.

  # Allow any size.
  MIN_SIZE_TEST: 0
  MAX_SIZE_TEST: 2048

MODEL:
  BACKBONE:
    FREEZE_AT: 2
  RPN:
    # This is effectively the
    # max number of detections
    POST_NMS_TOPK_TEST: 512
    PRE_NMS_TOPK_TEST: 512
  ROI_HEADS:
    # Low thresh, we filter later
    SCORE_THRESH_TEST: 0.2
  ANCHOR_GENERATOR:
    SIZES: [[32], [64], [128], [256], [512]]
    ASPECT_RATIOS: [[0.5, 1.0, 2.0]]

TEST:
    DETECTIONS_PER_IMAGE: 512
    AUG:
      ENABLED: False

CUDNN_BENCHMARK: true
VIS_PERIOD: 0
