base_config: base_detectron.yaml

data:
  train: data/restor-tcd-oam/train_20221010.json
  validation: data/restor-tcd-oam/val_20221010.json
  test: data/restor-tcd-oam/test_20221010.json
  tile_size: 1024

model:
  config: detectron2/detectron_mask_rcnn_test.yaml
  wandb_project: ci_instance_segmentation
  eval_after_train: False

postprocess:
  cleanup: false