base_config: train_kfold0_semantic.yaml

data:
  train: checkpoints/kfold_1/train.json
  validation: checkpoints/kfold_1/test.json
  test: checkpoints/kfold_1/test.json
  output: output/semantic/kfold_1
  data_root: checkpoints/kfold_1

model:
  weights: checkpoints/kfold_1/unet_resnet34.ckpt