base_config: train_kfold0_semantic.yaml

data:
  train: checkpoints/kfold_4/train.json
  validation: checkpoints/kfold_4/test.json
  test: checkpoints/kfold_4/test.json
  output: output/semantic/kfold_4
  data_root: checkpoints/kfold_4

model:
  weights: checkpoints/kfold_4/unet_resnet34.ckpt