base_config: train_kfold0_detectron.yaml

data:
  train: checkpoints/kfold_3/train.json
  validation: checkpoints/kfold_3/test.json
  test: checkpoints/kfold_3/test.json
  output: output/kfold_3

model:
  weights: "../checkpoints/kfold_3/model_final.pth"