base_config: train_kfold0_semantic.yaml

data:
  train: checkpoints/kfold_2/train.json
  validation: checkpoints/kfold_2/test.json
  test: checkpoints/kfold_2/test.json
  output: output/semantic/kfold_2
  data_root: checkpoints/kfold_2

model:
  weights: checkpoints/kfold_2/unet_resnet34.ckpt