defaults:
  - semantic_segmentation/unet_resnet34@_here_

weights: restor/tcd-segformer-mit-b0
name: segformer
backbone: nvidia/mit-b0
learning_rate: 5e-4

trainer:
  gpus: 1
  min_epochs: 1
  max_epochs: 1
  auto_lr_find: True
  auto_scale_batch_size: True
  precision: 16
  early_stopping_patience: 15
  max_time: 00:23:50:00
  debug_run: True

datamodule:
  augment: on

wandb:
  project_name: ci-testing