defaults:
  - semantic_segmentation/segformer-mit-b0@_here_

batch_size: 1

trainer:
  gpus: 1
  min_epochs: 1
  max_epochs: 1
  auto_lr_find: True
  auto_scale_batch_size: True
  precision: 16
  early_stopping_patience: 15
  max_time: 00:23:50:00
  debug_run: True

wandb:
  project_name: ci-testing