weights: "checkpoints/unet_resnet34.ckpt"
device: cuda
task: semantic_segmentation
log_dir: logs
num_workers: 8
tta: false

experiment:
  setup: False
  factor: 1
  sweep: False

trainer:
  gpus: 1
  min_epochs: 1
  max_epochs: 500
  auto_lr_find: False
  auto_scale_batch_size: False
  precision: 16
  early_stopping_patience: 10
  max_time: 00:48:00:00
  debug_run: False

config:
  loss: focal
  model: unet
  backbone: resnet50
  learning_rate: 1e-3
  pretrained: True
  learning_rate_schedule_patience: 5
  weights: imagenet
  in_channels: 3  
  num_classes: 2

datamodule:
  batch_size: 4
  num_workers: 8
  augment: on

wandb:
  project_name: vanilla-model-stable
