base_config: base.yaml

data:
  tile_size: 2048
  tile_overlap: 512

model:
  weights: "../checkpoints/unet_resnet34.ckpt"
  device: cuda
  task: semantic_segmentation
  config: torchgeo/unet_resnet34.yaml
  log_dir: logs
  num_workers: 8
  tta: false

postprocess:
  cache_format: numpy
  merge_classes: []