base_config: base.yaml

data:
  tile_size: 1024
  tile_overlap: 256

model:
  weights: "../checkpoints/unet_resnet34.ckpt"
  device: cuda
  task: semantic_segmentation
  config: torchgeo/unet_resnet34.yaml
  log_dir: logs
  num_workers: 8

postprocess:
  cache_format: numpy
  merge_classes: []