config_root: "config"

data:
  train: data/restor-tcd-oam/train_20221010_noempty.json
  validation: data/restor-tcd-oam/val_20221010_noempty.json
  test:
    - data/restor-tcd-oam/test_20221010_noempty.json
    - data/restor-tcd-oam/test_20221215_gold.json
  data_root: data/restor-tcd-oam
  images: data/restor-tcd-oam/images
  output: output
  push_to_bucket: gs://push/to/bucket
  format: mscoco
  name: tcd
  gsd: 0.1
  tile_size: 1024
  tile_overlap: 256
  classes:
    - canopy
    - tree
  grayscale: false

preprocess:
  bounds_check: true
  remove_border:
    radius: 10
  min_size:
    tree: 30
    canopy: 30
  max_size: 100
  merge_touching:
    threshold: 2
  merge_enclosed: true

postprocess:
  iou_threshold: 0.7
  iou_tiles: 0
  min-size:
    tree: 30
    canopy: 30
  max-size: 100
  cache_folder: "./temp"
  stateful: true
  debug_images: false
  cache_format: pickle
  use_nms: true
  confidence_threshold: 0.2
  segmentation_merge_pad: 32
  merge_classes:
    - canopy

evaluate:
  metrics:
    - coco
    - pdq
