base_config: base.yaml

data:
  tile_size: 2048
  tile_overlap: 256

model:
  weights: "../checkpoints/unet_resnet34.ckpt"
  device: cuda
  task: semantic_segmentation
  config: torchgeo/unet_resnet34.yaml

postprocess:
  cache_format: numpy
  merge_classes: []