base_config: base.yaml
model:
  architecture: "COCO-InstanceSegmentation/mask_rcnn_R_50_FPN_3x.yaml"
  task: "instance_segmentation"
  weights: "./checkpoints/model_final.pth"
  device: cuda
  config: detectron_mask_rcnn.yaml
  tta_batch_size: 1
  train_pretrained: True