base_config: base_semantic_segmentation.yaml

data:
  train: checkpoints/kfold_0/train.json
  validation: checkpoints/kfold_0/test.json
  test: checkpoints/kfold_0/test.json
  output: output/semantic/kfold_0
  data_root: checkpoints/kfold_0
  tile_size: 1024

model:
  weights: "../checkpoints/unet_resnet34.ckpt"
  device: cuda
  task: semantic_segmentation
  config: torchgeo/unet_resnet34.yaml
  log_dir: logs
  num_workers: 8
  tta: false
  pretrained: true