base_config: train_kfold0_detectron.yaml

data:
  train: checkpoints/kfold_2/train.json
  validation: checkpoints/kfold_2/test.json
  test: checkpoints/kfold_2/test.json
  output: output/kfold_2

model:
  weights: "../checkpoints/kfold_2/model_final.pth"