name: Build Dockerfile

on: [push]

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Log in to the Container registry
        uses: docker/login-action@f054a8b539a109f9f41c372932f1ae047eff08c9
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@98669ae865ea3cffbcbaa878cf57c20bbf1c6c38
        with:
          images: ghcr.io/${{ github.repository }}
      - name: Get repo
        uses: actions/checkout@v3
      - name: Clone repo into subdir for Docker build
        uses: actions/checkout@v3
        with:
          path: docker/docker-tcd-pipeline
      - name: Download detectron checkpoint
        uses: robinraju/release-downloader@v1.6
        with:
          repository: "Restor-Foundation/tcd-pipeline"
          tag: "init"
          fileName: "model_final.pth"
          out-file-path: "docker/checkpoints"
      - name: Download semantic segmentation checkpoint
        uses: robinraju/release-downloader@v1.6
        with:
          repository: "Restor-Foundation/tcd-pipeline"
          tag: "init"
          fileName: "unet_resnet34.ckpt"
          out-file-path: "docker/checkpoints"
      - name: Build and push Docker image
        uses: docker/build-push-action@ad44023a93711e3deb337508980b4b5e9bcdc5dc
        with:
          context: ./docker
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
