name: tests

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.10"]

    steps:
      - uses: actions/checkout@v3
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
      - name: install gdal
        run: sudo apt-get -y -qq -o Acquire::Retries=3 install gdal-bin
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip setuptools wheel
          python -m pip install torch torchvision
          python -m pip install -r requirements.txt
          python -m pip install -e .
      - name: Test with pytest
        env: # HuggingFace Hub login
          HF_TOKEN: ${{ secrets.HF_TOKEN }}
        run: |
          wandb offline
          pip install pytest
          pip install pytest-cov
          python -m pytest