name: Tests

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.10", "3.11", "3.12"]

    steps:
      - name: Attempt to remove big files
        run: sh -c "$(curl -sSL https://raw.githubusercontent.com/apache/flink/02d30ace69dc18555a5085eccf70ee884e73a16e/tools/azure-pipelines/free_disk_space.sh)"

      - name: Delete huge unnecessary tools folder
        run: rm -rf /opt/hostedtoolcache

      - uses: actions/checkout@v3
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
      - name: install gdal
        run: sudo apt-get -y -qq -o Acquire::Retries=3 install gdal-bin
      - name: Install dependencies
        run: |
          python -m pip install uv
          uv venv .venv
          uv pip install setuptools wheel torch
          uv sync --all-groups --no-build-isolation
      - name: Test with pytest
        env: # HuggingFace Hub login
          HF_TOKEN: ${{ secrets.HF_TOKEN }}
        run: |
          uv run wandb offline
          uv run pytest
      - name: Test generate dataset
        env:
          HF_TOKEN: ${{ secrets.HF_TOKEN }}
        run:
          uv run python tools/generate_dataset.py --folds restor/tcd restor/tcd-nc restor/tcd-sa dataset
      
